app:
  debug: true

server:
  port: '8080'
  error:
    include-message: always

spring:
  application:
    name: LibraryManagementSystem
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/lms_db
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  mvc:
    view:
      prefix: '/'
      suffix: '.html'
  security:
     debug: true
     redis:
       host: localhost
       port: 6379
       timeout: 60000
#    user:
#      name: admin
#      password: admin
logging:
  level:
    org.springframework.data.redis: DEBUG

